COMMON_FLAGS="-march=alderlake -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
PYTHON_TARGETS="python3_13"

MAKEOPTS="-j14"
EMERGE_DEFAULT_OPTS="--autounmask --autounmask-write --autounmask-continue --autounmask-unrestricted-atoms=y"
PORTAGE_NICENESS=1
USE="wayland xwayland vulkan vaapi pipewire vdpau elogind truetype harfbuzz -nvenc -gnome -kde -openrc -emacs -cups -test"

LC_MESSAGES=C.UTF-8
ACCEPT_KEYWORDS="amd64"
VIDEO_CARDS="radeonsi radeon amdgpu"
INPUT_DEVICES="libinput"
FEATURES="parallel-fetch parallel-install ccache"
CCACHE_DIR="/var/cache/ccache"
ABI_X86="32 64"
ACCEPT_LICENSE="*"


# Keeping to the side
# COMMON_FLAGS="-flto ${WARNING_FLAGS}"
# USE="lto"
# WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"


# Current specs
# os ~ : Gentoo Linux x86_64
# kr ~ : Linux gentoo-dist
# ds ~ : Wayland
# cp ~ : 12th Gen Intel(R) Core(TM) i5-12600K (16) @ 4.90 GHz
# gp ~ : AMD Radeon RX 6650 XT [Discrete]
# rm ~ : 31.17 GiB
